export const initialPlan = {
  is_sku: null,
  sku_expired_date: null,
  name: '',
  monthly_price: '',
  annual_price: '',
  mau_limit: 0,
  admin_agent_limit: 0,
  type: '',
  currency: 'IDR',
  subscription_date: '',
  subscription_type: '',
  subscription_status: '',
  extra_mau: 0,
  extra_mau_charge: '',
  plan_group: '',
  trial_remaining_days: null,
  usage_info: {
    mau_usage: 0,
    admin_agent_usage: 0,
    extra_mau: 0,
    extra_mau_charge: 0,
    current_mau: 0,
  },
  exclusive_user: {},
  max_wa_channel: 0,
};
