export const initUser = {
  id: 0,
  name: '',
  authentication_token: '',
  created_at: '',
  updated_at: '',
  is_available: false,
  type: 0,
  avatar_url: '',
  app_id: 0,
  is_verified: false,
  notifications_room_id: null,
  bubble_color: null,
  direct_login_token: '',
  last_login: '',
  force_offline: false,
  deleted_at: null,
  is_toc_agree: false,
  totp_token: '',
  is_req_otp_reset: null,
  last_password_update: '',
  type_as_string: '',
  assigned_rules: null,
  expired_on: 0,
  expiration_day: 0,
};

export const initSdkUser = {
  id: 0,
  token: '',
  display_name: '',
  avatar_url: '',
  extras: {
    type: '',
    user_bubble_color: '',
  },
};
